import bcrypt from 'bcryptjs';

export const data = {
	users: [
		{
			name: 'Francis',
			email: 'admin@example.com',
			password: bcrypt.hashSync('123456', 11),
			isAdmin: true,
		},
		{
			name: 'Jane',
			email: 'user@example.com',
			password: bcrypt.hashSync('123456', 11),
			isAdmin: false,
		},
	],
	products: [
		{
			name: 'Symmetrical Hoodie',
			slug: 'symmetrical-hoodie',
			category: 'Shirts',
			image: '/images/shirt1.jpg',
			price: 200,
			brand: 'Subwae',
			rating: 4.3,
			numReviews: 8,
			countInStock: 20,
			description:
				'Symmetrical Hoodie. Pure narrative momentum through garment construction',
		},
		{
			name: 'Look 1 SS Shirt',
			slug: 'look1-ss-shirt',
			category: 'Shirts',
			image: '/images/shirt2.jpg',
			price: 600,
			brand: 'Subwae',
			rating: 3.5,
			numReviews: 10,
			countInStock: 20,
			description: 'Collection 22/23. SUBWAE STUDIOS Shirt. Variant 1',
		},
		{
			name: 'Soulful Simplicity T',
			slug: 'ss-simplicity-T',
			category: 'Shirts',
			image: '/images/shirt3.jpg',
			price: 300,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 3,
			countInStock: 20,
			description:
				'Soulful Simplicity Look 4. Subwae Studios/22-23. Heavy cotton and boxed fit',
		},
		{
			name: 'AS Skuba Pants',
			slug: 'skuba-pants',
			category: 'Pants',
			image: '/images/pant1.jpg',
			price: 450,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'AS Skuba Pants. African Soil Collection. Very smooth and stretchy fabric. Vertical stripes accross the fabric',
		},
		{
			name: 'Complete Fit w/ Red Bag',
			slug: 'complete-fit-1',
			category: 'Pants',
			image: '/images/pant2.jpg',
			price: 899,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'Subwae African Soil collection RED strap bag with Soulful Simplicity Shirt and Skirt  ',
		},
		{
			name: 'Complete Fit w/ White Bag',
			slug: 'complete-fit-2',
			category: 'Pants',
			image: '/images/pant3.jpg',
			price: 899,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'Subwae African Soil collection GRAY strap bag with Soulful Simplicity Shirt and Skirt',
		},
		{
			name: 'Camper',
			slug: 'camper',
			category: 'Cap',
			image: '/images/cap1.jpg',
			price: 50,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description: 'Nylon camper lightweight headwear',
		},
		{
			name: 'SS BAG',
			slug: 'ss-bag',
			category: 'Bag',
			image: '/images/bag1.jpg',
			price: 70,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description: 'Soulful Simplicity 22/23 Collection. Strap Bag',
		},
		{
			name: '404 Error T',
			slug: '404-error-t',
			category: 'T-Shirts',
			image: '/images/errorT.jpg',
			price: 99,
			brand: 'Subwae',
			rating: 4.0,
			numReviews: 13,
			countInStock: 20,
			description:
				'Soulful Simplicity 22/23 Collection. For the Software Developer',
		},
	],
	productList: [
		{
			name: 'Magic Face Primer',
			slug: 'magic-face-primer',
			category: ['All Categories', 'Maybelline'],
			image: '/images/pomade1.jpg',
			discount: '50%',
			priceDisplay: '4,850',
			priceDiscountedDisplay: '4,900',
			priceDiscounted: 4900,
			price: 4850,
			rating: 4.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This formular is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'MICELLAR WATER',
			slug: 'micellar-water',
			category: ['All Categories', 'Body Oil', 'Perfumes'],
			image: '/images/spray1.jpg',
			discount: '50%',
			priceDisplay: '4,900',
			priceDiscountedDisplay: '11,950',
			priceDiscounted: 11950,
			price: 4900,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This formular is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'FACE PRIMER',
			slug: 'face-primer',
			category: ['All Categories', 'Face Masks'],
			image: '/images/pomade2.jpg',
			priceDisplay: '5,900',
			price: 5900,
			rating: 4.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This face mask is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'TONIC LOTION',
			slug: 'tonic-lotion',
			category: ['All Categories', 'Foundation'],
			image: '/images/spray2.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 4.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This lotion is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'FILM EYESHADOW',
			slug: 'film-eyeshadow',
			category: ['All Categories', 'Face Masks'],
			image: '/images/pomade3.jpg',
			discount: '50%',
			priceDisplay: '5,000',
			priceDiscountedDisplay: '11,900',
			priceDiscounted: 11900,
			price: 5000,
			rating: 4.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This eyeshadow is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'FACE PRIMER',
			slug: 'face-primer-2',
			category: ['All Categories', 'Guerlain', 'Lip Gloss'],
			image: '/images/lipstick1.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 4.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This gloss is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'TONIC LOTION',
			slug: 'tonic-lotion-2',
			category: ['All Categories', 'Cosmetic'],
			image: '/images/pomade4.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This lotion is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'MICELLAR WATER',
			slug: 'micellar-water-2',
			category: ['All Categories', 'Applicators', 'Perfumes'],
			image: '/images/spray3.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 2,
			description:
				'This perfume is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'SKIN PRIMER',
			slug: 'skin-primer-1',
			category: ['All Categories', 'Skin Solutions'],
			image: '/images/skin1.jpg',
			priceDisplay: '5,950',
			price: 5950,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 2,
			description:
				'This skin solution is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'FILM EYESHADOW',
			slug: 'film-eyeshadow-2',
			category: ['All Categories', 'Cosmetic', 'Guerlain'],
			image: '/images/eyeshadow1.jpg',
			discount: '50%',
			priceDisplay: '5,000',
			priceDiscountedDisplay: '11,950',
			priceDiscounted: 11950,
			price: 5000,
			rating: 4.0,
			countInStock: 20,
			numOfReviews: 5,
			description:
				'This eyeshadow is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'TONIC LOTION',
			slug: 'tonic-lotion-3',
			category: ['All Categories', 'Body Oil'],
			image: '/images/bodyoil1.jpg',
			priceDisplay: '50',
			price: 50,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 2,
			description:
				'This body oil is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'MICELLAR WATER',
			slug: 'micellar-water-3',
			category: ['All Categories', 'Skin Solutions'],
			image: '/images/face1.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This skin solution is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'FILM EYESHADOW',
			slug: 'film-eyeshadow-3',
			category: ['All Categories', 'Body Oil'],
			image: '/images/balsam.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This body oil is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'MICELLAR WATER',
			slug: 'micellar-water-4',
			category: ['All Categories', 'Applicators'],
			image: '/images/apply1.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This formular is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'TONIC LOTION',
			slug: 'tonic-lotion-4',
			category: ['All Categories', 'Skin Solutions'],
			image: '/images/lotion1.jpg',
			priceDisplay: '5,000',
			price: 5000,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 1,
			description:
				'This lotion is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'FILM EYESHADOW',
			slug: 'film-eyeshadow-4',
			category: ['All Categories', 'Perfumes'],
			image: '/images/eyeshadow4.jpg',
			discount: '50%',
			priceDisplay: '5,000',
			priceDiscountedDisplay: '11,950',
			priceDiscounted: 11950,
			price: 5000,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 8,
			description:
				'This eyeshadow is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'ELEGANTE WATCH',
			slug: 'elegante-watch',
			category: ['All Categories', 'Watch'],
			image: '/images/watch.jpg',
			priceDisplay: '10',
			price: 10,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 8,
			description:
				'This watch is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
		{
			name: 'ELEGANTE NECKLACE',
			slug: 'elegante-necklace',
			category: ['All Categories', 'Watch'],
			image: '/images/necklace.jpg',
			priceDisplay: '10',
			price: 10,
			rating: 5.0,
			countInStock: 20,
			numOfReviews: 8,
			description:
				'This necklace is inspired by Classic Retro and Vintage apparel, headlines, signage, logo, quote, apparel and other creative applications.',
		},
	],
};
